spring.datasource.url=jdbc:h2:mem:db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true

logging.level.root=INFO
logging.level.ua.fictionallibrary=DEBUG

spring.web.error.include-message=always
spring.web.error.include-stacktrace=on_param
spring.web.error.include-binding-errors=always

management.endpoints.web.exposure.include=*
